<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>co</string>
	</array>
	<key>name</key>
	<string>CO Positive DSL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.formulaId</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*#\s*(id\s*:)</string>
			<key>name</key>
			<string>meta.id</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\#.*</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string_quoted_single_multiline</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\$)?([A-Za-z_]\w*(\.\w+)+)</string>
			<key>name</key>
			<string>meta.identifier</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[|?+*]</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(==|!=|&lt;=|&gt;=|=|\+|\-|\*|&gt;|&lt;)</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(div|mod|and|or|not)\b</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+[dhms]\b</string>
			<key>name</key>
			<string>constant.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\d+(\.\d+)?)\b</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(null|true|false)\b</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(exec_query|any)\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(event|rule|aggregate)\b</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(within|with different|timer|sorted_key|query|on|notify|key|from|filter|emit)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\$)?([A-Za-z_]\w*)</string>
			<key>name</key>
			<string>meta.identifier</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>escaped_char</key>
		<dict>
			<key>match</key>
			<string>\\.</string>
			<key>name</key>
			<string>constant.character.escape</string>
		</dict>
		<key>string_quoted_single_multiline</key>
		<dict>
			<key>begin</key>
			<string>('|")</string>
			<key>end</key>
			<string>\1</string>
			<key>name</key>
			<string>string.quoted.single.multiline</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped_char</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.co_dsl</string>
	<key>uuid</key>
	<string>d3894f6f-6a51-41d7-b2cb-497a4286c142</string>
</dict>
</plist>
