<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>XP non-text Format String</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.tokenGroup</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.constant.var_or_expr</string>
						</dict>
					</dict>
					<key>match</key>
					<string>((\$?)[.\w]+)\s*(=)\s*([.\w]+)</string>
					<key>name</key>
					<string>meta.assignment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#space</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#anyother</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\w+</string>
			<key>name</key>
			<string>support.constant.var_or_expr</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>anyother</key>
		<dict>
			<key>match</key>
			<string>.</string>
			<key>name</key>
			<string>invalid.illegal</string>
		</dict>
		<key>space</key>
		<dict>
			<key>match</key>
			<string>\s</string>
			<key>name</key>
			<string>meta.space</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.xp_formatstring.other</string>
	<key>uuid</key>
	<string>eaa584a4-9f0e-42e7-a9b3-e17a8a2dbbe8</string>
</dict>
</plist>
