<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>XP TEXT Format String</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.tokenGroup</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_quoted_single_multiline</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[|?+*]</string>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\$?)([.\w]+)\s*(=)</string>
					<key>name</key>
					<string>meta.assignment</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(WORDDASH|WORD|DATETIME|HOSTNAME|NUMBER|LITERAL|STRING|IPV4|IPV6|MACADDR|NTUSER|REST)\b</string>
					<key>name</key>
					<string>support.constant.token</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#escaped_char</string>
		</dict>
		<dict>
			<key>match</key>
			<string>.</string>
			<key>name</key>
			<string>string</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>escaped_char</key>
		<dict>
			<key>match</key>
			<string>\\.</string>
			<key>name</key>
			<string>constant.character.escape</string>
		</dict>
		<key>string_quoted_single_multiline</key>
		<dict>
			<key>begin</key>
			<string>('|")</string>
			<key>end</key>
			<string>\1</string>
			<key>name</key>
			<string>string.quoted.single.multiline</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped_char</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.xp_formatstring.text</string>
	<key>uuid</key>
	<string>40b05e72-3616-4f2b-a954-867b6dd43deb</string>
</dict>
</plist>
