<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>xp</string>
	</array>
	<key>name</key>
	<string>XP Positive DSL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.formulaId</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*#\s*(id\s*:)</string>
			<key>name</key>
			<string>meta.formulaId</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\#.*</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.cond</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*!?(COND)\s*=</string>
			<key>name</key>
			<string>meta.cond</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*!?(TEXT|FORMAT)\s*=\s*('|")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.formatSpecifier</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.xp_formatstring.text</string>
			<key>end</key>
			<string>\2</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.xp_formatstring.text</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*!?(JSON|TABULAR|EVENTLOG|XML)\s*=\s*('|")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.formatSpecifier</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.formatString.other</string>
			<key>end</key>
			<string>\2</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.xp_formatstring.other</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#string_quoted_single_multiline</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\$)?([A-Za-z_]\w*(\.\w+)+)</string>
			<key>name</key>
			<string>meta.identifier</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(==|!=|&lt;=|&gt;=|=|\+|\-|\*|&gt;|&lt;)</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(div|mod|and|or|not)\b</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(endif|elif|if|then|else|endswitch|case|switch)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\d+(\.\d+)?)\b</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(null|true|false)\b</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(string|number16|number8|number|float|duration|macaddr|ipv4|ipv6|datetime|bool|keyvalue| maybe_number16|maybe_number8|maybe_number|maybe_float|maybe_duration|maybe_macaddr|maybe_ipv4|maybe_ipv6|maybe_datetime| epoch_to_datetime|epoch_ms_to_datetime|datetime_to_epoch|datetime_to_epoch_ms|win_ticks_to_datetime|datetime_to_win_ticks)\b</string>
			<key>name</key>
			<string>support.function.type_conversion_funcs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(length|coalesce)\b</string>
			<key>name</key>
			<string>support.function.general_utils</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(append|remove|in_list)\b</string>
			<key>name</key>
			<string>support.function.list_utils</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(in_subnet)\b</string>
			<key>name</key>
			<string>support.function.ip_utils</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(year|month|day|hour|minute|second|timezone)\b</string>
			<key>name</key>
			<string>support.function.datetime_utils</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(strip|substr|find_substr|match|upper|lower)\b</string>
			<key>name</key>
			<string>support.function.str_regex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(count_window|window_to_list)\b</string>
			<key>name</key>
			<string>support.function.window_utils</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(in_active_set)\b</string>
			<key>name</key>
			<string>support.function.active_set</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(pow|abs|floor|ceil|sign)\b</string>
			<key>name</key>
			<string>support.function.maths</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(drop|emit|close|store_current_message)\b</string>
			<key>name</key>
			<string>support.function.correla</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(append|remove|append_window|active_set_insert|active_set_remove)\b</string>
			<key>name</key>
			<string>support.function.lists</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(submessage)\b</string>
			<key>name</key>
			<string>support.function.normali</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(endsubformula|subformula)\b</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\$)?([A-Za-z_]\w*)</string>
			<key>name</key>
			<string>meta.identifier</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>anyother</key>
		<dict>
			<key>match</key>
			<string>.</string>
			<key>name</key>
			<string>invalid.illegal</string>
		</dict>
		<key>escaped_char</key>
		<dict>
			<key>match</key>
			<string>\\.</string>
			<key>name</key>
			<string>constant.character.escape</string>
		</dict>
		<key>space</key>
		<dict>
			<key>match</key>
			<string>\s</string>
			<key>name</key>
			<string>meta.space</string>
		</dict>
		<key>string_quoted_single_multiline</key>
		<dict>
			<key>begin</key>
			<string>('|")</string>
			<key>end</key>
			<string>\1</string>
			<key>name</key>
			<string>string.quoted.single.multiline</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped_char</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.xp_dsl</string>
	<key>uuid</key>
	<string>63c2678b-9ea6-4cd6-b7a2-69f764e70ac6</string>
</dict>
</plist>
